//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Visit", Namespace="http://schemas.datacontract.org/2004/07/PolyclinicService")]
    public partial class Visit : object
    {
        
        private System.DateTime DateField;
        
        private string DoctorFioField;
        
        private int IdField;
        
        private string PatientFioField;
        
        private string SpecialityField;

        public Visit(string doctorFio, string patientFio, DateTime date, string speciality)
        {
            DoctorFio = doctorFio;
            PatientFio = patientFio;
            Date = date;
            Speciality = speciality;
        }

        public Visit(int id, string doctorFio, string patientFio, DateTime date, string speciality)
        {
            Id = id;
            DoctorFio = doctorFio;
            PatientFio = patientFio;
            Date = date;
            Speciality = speciality;
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DoctorFio
        {
            get
            {
                return this.DoctorFioField;
            }
            set
            {
                this.DoctorFioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientFio
        {
            get
            {
                return this.PatientFioField;
            }
            set
            {
                this.PatientFioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Speciality
        {
            get
            {
                return this.SpecialityField;
            }
            set
            {
                this.SpecialityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/PolyclinicService")]
    public partial class Token : object
    {
        
        private System.DateTime Day1Field;
        
        private System.DateTime Day2Field;
        
        private ServiceReference1.Functions FunctionField;
        
        private int IdField;
        
        private string LineField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Day1
        {
            get
            {
                return this.Day1Field;
            }
            set
            {
                this.Day1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Day2
        {
            get
            {
                return this.Day2Field;
            }
            set
            {
                this.Day2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Functions Function
        {
            get
            {
                return this.FunctionField;
            }
            set
            {
                this.FunctionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line
        {
            get
            {
                return this.LineField;
            }
            set
            {
                this.LineField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Functions", Namespace="http://schemas.datacontract.org/2004/07/PolyclinicService")]
    public enum Functions : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Create = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Get = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenPaymentDto", Namespace="http://schemas.datacontract.org/2004/07/PolyclinicService")]
    public partial class TokenPaymentDto : object
    {
        
        private System.DateTime Date1Field;
        
        private System.DateTime Date2Field;
        
        private ServiceReference1.Functions dataField;


        public TokenPaymentDto(Functions get, DateTime day1, DateTime day2)
        {
            this.dataField = get;
            this.Date1Field = day1;
            this.Date2Field = day2;
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date1
        {
            get
            {
                return this.Date1Field;
            }
            set
            {
                this.Date1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date2
        {
            get
            {
                return this.Date2Field;
            }
            set
            {
                this.Date2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Functions data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPolyclinicService")]
    public interface IPolyclinicService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolyclinicService/GetVisits", ReplyAction="http://tempuri.org/IPolyclinicService/GetVisitsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Visit[]> GetVisitsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolyclinicService/CreateVisit", ReplyAction="http://tempuri.org/IPolyclinicService/CreateVisitResponse")]
        System.Threading.Tasks.Task<bool> CreateVisitAsync(ServiceReference1.Visit visit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolyclinicService/UpdateVisit", ReplyAction="http://tempuri.org/IPolyclinicService/UpdateVisitResponse")]
        System.Threading.Tasks.Task<bool> UpdateVisitAsync(ServiceReference1.Visit visit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolyclinicService/DeleteVisit", ReplyAction="http://tempuri.org/IPolyclinicService/DeleteVisitResponse")]
        System.Threading.Tasks.Task<bool> DeleteVisitAsync(ServiceReference1.Visit visit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolyclinicService/getTokenPayments", ReplyAction="http://tempuri.org/IPolyclinicService/getTokenPaymentsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Token[]> getTokenPaymentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolyclinicService/PayToken", ReplyAction="http://tempuri.org/IPolyclinicService/PayTokenResponse")]
        System.Threading.Tasks.Task PayTokenAsync(ServiceReference1.TokenPaymentDto tokenDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolyclinicService/IsTokenExists", ReplyAction="http://tempuri.org/IPolyclinicService/IsTokenExistsResponse")]
        System.Threading.Tasks.Task<bool> IsTokenExistsAsync(ServiceReference1.Functions functions);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPolyclinicServiceChannel : ServiceReference1.IPolyclinicService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PolyclinicServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IPolyclinicService>, ServiceReference1.IPolyclinicService
    {
        
        public PolyclinicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }

        public PolyclinicServiceClient()
        {
        }

        public System.Threading.Tasks.Task<ServiceReference1.Visit[]> GetVisitsAsync()
        {
            return base.Channel.GetVisitsAsync();
        }
        
        public System.Threading.Tasks.Task<bool> CreateVisitAsync(ServiceReference1.Visit visit)
        {
            return base.Channel.CreateVisitAsync(visit);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateVisitAsync(ServiceReference1.Visit visit)
        {
            return base.Channel.UpdateVisitAsync(visit);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteVisitAsync(ServiceReference1.Visit visit)
        {
            return base.Channel.DeleteVisitAsync(visit);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Token[]> getTokenPaymentsAsync()
        {
            return base.Channel.getTokenPaymentsAsync();
        }
        
        public System.Threading.Tasks.Task PayTokenAsync(ServiceReference1.TokenPaymentDto tokenDto)
        {
            return base.Channel.PayTokenAsync(tokenDto);
        }
        
        public System.Threading.Tasks.Task<bool> IsTokenExistsAsync(ServiceReference1.Functions functions)
        {
            return base.Channel.IsTokenExistsAsync(functions);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
